version: '3.8'

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    image: local-actions-runner:latest
    container_name: hello-there-runner
    restart: unless-stopped
    environment:
      REPO_URL: ${REPO_URL}
      GITHUB_RUNNER_TOKEN: ${GITHUB_RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME:-hello-there-runner}
      RUNNER_LABELS: ${RUNNER_LABELS:-self-hosted,linux,docker}
      RUNNER_WORK: /runner/_work
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_work:/runner/_work
      - /tmp:/tmp
    networks:
      - runner-network
    healthcheck:
      test:
        - CMD
        - pgrep
        - -f
        - Runner.Worker
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  runner_work:
    driver: local

networks:
  runner-network:
    driver: bridge