version: "3.8"
services:
  gha-runner:
    image: local-actions-runner:latest
    restart: unless-stopped
    environment:
      REPO_URL: "${REPO_URL}"
      RUNNER_TOKEN: "${GITHUB_RUNNER_TOKEN}"
      RUNNER_NAME: "home-runner"
      RUNNER_LABELS: "self-hosted,home,docker"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_work:/runner/_work
volumes:
  runner_work: